# Generated by Django 5.2.17 on 2026-09-26 17:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('scale', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'currencies',
                'constraints': [models.CheckConstraint(condition=models.Q(('scale__lte', 18)), name='currency_scale_fits_storage')],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_id', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense')], max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen')], default='active', max_length=16)),
                ('allow_overdraft', models.BooleanField(default=False)),
                ('is_settlement', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='ledger.apiclient')),
                ('currency', models.ForeignKey(db_column='currency', on_delete=django.db.models.deletion.PROTECT, to='ledger.currency')),
            ],
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('request_hash', models.CharField(max_length=64)),
                ('response_status', models.PositiveSmallIntegerField(null=True)),
                ('response_body', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.apiclient')),
            ],
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aggregate_type', models.CharField(max_length=32)),
                ('aggregate_id', models.UUIDField()),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'indexes': [models.Index(condition=models.Q(('published_at__isnull', True)), fields=['created_at'], name='outbox_unpublished')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer'), ('journal', 'Journal'), ('hold_capture', 'Hold Capture'), ('reversal', 'Reversal')], max_length=16)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='ledger.apiclient')),
                ('reverses', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='ledger.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Hold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=38)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('captured', 'Captured'), ('released', 'Released')], default='active', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holds', to='ledger.account')),
                ('capture_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='captured_hold', to='ledger.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=18, max_digits=38)),
                ('currency', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.account')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ledger.transaction')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
        migrations.CreateModel(
            name='BalanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of_entry_id', models.BigIntegerField()),
                ('balance', models.DecimalField(decimal_places=18, max_digits=38)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='ledger.account')),
            ],
            options={
                'indexes': [models.Index(models.F('account'), models.OrderBy(models.F('as_of_entry_id'), descending=True), name='snapshot_latest')],
                'constraints': [models.UniqueConstraint(fields=('account', 'as_of_entry_id'), name='one_snapshot_per_account_entry')],
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['client', 'owner_id'], name='ledger_acco_client__dec47b_idx'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('is_settlement', True)), fields=('client', 'currency'), name='one_settlement_account_per_client_currency'),
        ),
        migrations.AddConstraint(
            model_name='idempotencyrecord',
            constraint=models.UniqueConstraint(fields=('client', 'key'), name='idempotency_key_per_client'),
        ),
        migrations.AddIndex(
            model_name='hold',
            index=models.Index(condition=models.Q(('status', 'active')), fields=['account'], name='hold_active_by_account'),
        ),
        migrations.AddConstraint(
            model_name='hold',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='hold_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='hold',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('capture_transaction__isnull', False), ('status', 'captured')), models.Q(models.Q(('status', 'captured'), _negated=True), ('capture_transaction__isnull', True)), _connector='OR'), name='hold_captured_iff_transaction'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['account', 'id'], name='ledger_entr_account_ba219e_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['account', 'created_at'], name='ledger_entr_account_b86ea8_idx'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='entry_amount_nonzero'),
        ),
    ]
