# Generated by Django 5.2.17 on 2026-09-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_seed_currencies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idempotencyrecord',
            name='response_body',
            field=models.TextField(blank=True, default=''),
        ),
    ]
